COLOUMNS: 
  age: int64
  fnlwgt: int64
  educational-num: int64
  gender: int64
  capital-gain: int64
  capital-loss: int64
  hours-per-week: int64
  occupation_?: int64
  occupation_Adm-clerical: int64
  occupation_Armed-Forces: int64
  occupation_Craft-repair: int64
  occupation_Exec-managerial: int64
  occupation_Farming-fishing: int64
  occupation_Handlers-cleaners: int64
  occupation_Machine-op-inspct: int64
  occupation_Other-service: int64
  occupation_Priv-house-serv: int64
  occupation_Prof-specialty: int64
  occupation_Protective-serv: int64
  occupation_Sales: int64
  occupation_Tech-support: int64
  occupation_Transport-moving: int64
  workclass_?: int64
  workclass_Federal-gov: int64
  workclass_Local-gov: int64
  workclass_Never-worked: int64
  workclass_Private: int64
  workclass_Self-emp-inc: int64
  workclass_Self-emp-not-inc: int64
  workclass_State-gov: int64
  workclass_Without-pay: int64
  marital-status_Divorced: int64
  marital-status_Married-AF-spouse: int64
  marital-status_Married-civ-spouse: int64
  marital-status_Married-spouse-absent: int64
  marital-status_Never-married: int64
  marital-status_Separated: int64
  marital-status_Widowed: int64
  relationship_Husband: int64
  relationship_Not-in-family: int64
  relationship_Other-relative: int64
  relationship_Own-child: int64
  relationship_Unmarried: int64
  relationship_Wife: int64
  race_Amer-Indian-Eskimo: int64
  race_Asian-Pac-Islander: int64
  race_Black: int64
  race_Other: int64
  race_White: int64
  native-country_?: int64
  native-country_Cambodia: int64
  native-country_Canada: int64
  native-country_China: int64
  native-country_Columbia: int64
  native-country_Cuba: int64
  native-country_Dominican-Republic: int64
  native-country_Ecuador: int64
  native-country_El-Salvador: int64
  native-country_England: int64
  native-country_France: int64
  native-country_Germany: int64
  native-country_Greece: int64
  native-country_Guatemala: int64
  native-country_Haiti: int64
  native-country_Holand-Netherlands: int64
  native-country_Honduras: int64
  native-country_Hong: int64
  native-country_Hungary: int64
  native-country_India: int64
  native-country_Iran: int64
  native-country_Ireland: int64
  native-country_Italy: int64
  native-country_Jamaica: int64
  native-country_Japan: int64
  native-country_Laos: int64
  native-country_Mexico: int64
  native-country_Nicaragua: int64
  native-country_Outlying-US(Guam-USVI-etc): int64
  native-country_Peru: int64
  native-country_Philippines: int64
  native-country_Poland: int64
  native-country_Portugal: int64
  native-country_Puerto-Rico: int64
  native-country_Scotland: int64
  native-country_South: int64
  native-country_Taiwan: int64
  native-country_Thailand: int64
  native-country_Trinadad&Tobago: int64
  native-country_United-States: int64
  native-country_Vietnam: int64
  native-country_Yugoslavia: int64


TARGET_COLUMN:
  name: income